AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcId:
    Description: VPC ID
    Default: 'vpc-92d813f9'
    Type: AWS::EC2::VPC::Id
  InstanceName:
    Description: Instance name
    Default: 'Cli-Redis'
    Type: String
  InstanceUser:
    Description: Instance user name
    Default: ''
    Type: String

  InstanceType:
    AllowedValues:
      # General purpose
      - a1.medium
      - a1.large
      - a1.xlarge
      - a1.2xlarge
      - a1.4xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m4.16xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - m5.24xlarge
      - m5.metal
      - m5a.large
      - m5a.xlarge
      - m5a.2xlarge
      - m5a.4xlarge
      - m5a.12xlarge
      - m5a.24xlarge
      - m5d.large
      - m5d.xlarge
      - m5d.2xlarge
      - m5d.4xlarge
      - m5d.12xlarge
      - m5d.24xlarge
      - m5d.metal
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      # Compute optimized
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.18xlarge
      - c5d.xlarge
      - c5d.2xlarge
      - c5d.4xlarge
      - c5d.9xlarge
      - c5d.18xlarge
      - c5n.large
      - c5n.xlarge
      - c5n.2xlarge
      - c5n.4xlarge
      - c5n.9xlarge
      - c5n.18xlarge
      # Memory optimized
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.12xlarge
      - r5.24xlarge
      - r5.metal
      - r5a.large
      - r5a.xlarge
      - r5a.2xlarge
      - r5a.4xlarge
      - r5a.12xlarge
      - r5a.24xlarge
      - r5d.large
      - r5d.xlarge
      - r5d.2xlarge
      - r5d.4xlarge
      - r5d.12xlarge
      - r5d.24xlarge
      - r5d.metal
      - u-6tb1.metal
      - u-9tb1.metal
      - u-12tb1.metal
      - x1.16xlarge
      - x1.32xlarge
      - x1e.xlarge
      - x1e.2xlarge
      - x1e.4xlarge
      - x1e.8xlarge
      - x1e.16xlarge
      - x1e.32xlarge
      - z1d.large
      - z1d.xlarge
      - z1d.2xlarge
      - z1d.3xlarge
      - z1d.6xlarge
      - z1d.12xlarge
      - z1d.metal
      # Storage optimized
      - d2.xlarge
      - d2.2xlarge
      - d2.4xlarge
      - d2.8xlarge
      - h1.2xlarge
      - h1.4xlarge
      - h1.8xlarge
      - h1.16xlarge
      - i3.large
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
      - i3.16xlarge
      - i3.metal
      # Accelerated computing
      - f1.2xlarge
      - f1.4xlarge
      - f1.16xlarge
      - g3s.xlarge
      - g3.4xlarge
      - g3.8xlarge
      - g3.16xlarge
      - p2.xlarge
      - p2.8xlarge
      - p2.16xlarge
      - p3.2xlarge
      - p3.8xlarge
      - p3.16xlarge
      - p3dn.24xlarge
    Default: 't2.micro'
    Description: Select instance type
    Type: String
  InstnaceImageID:
    Default: 'ami-04d98b9c7871e56b7'
    Description: Amazon Machine ID to use for the instance
    Type: String
  InstanceKeyName:
    Default: 'mumbai-ec2'
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
  InstanceSubnet:
    Default: 'subnet-0b1a592de659a02a2'
    Description: Subnets for Application
    Type: AWS::EC2::Subnet::Id
  
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: 'Instance Configuration'
      Parameters:
        - InstanceName
        - InstanceUser
        - InstnaceImageID
        - InstanceType

        - InstanceKeyName
    - Label:
        default: 'Network Configuration'
      Parameters:
        - VpcId
        - InstanceSubnet
    ParameterLabels:
      VpcId:
        default: VPC ID
      InstanceName:
        default: Name
      InstanceUser:
        default: User
      InstnaceImageID:
        default: Image ID
      InstanceType:
        default: Instance Type
      InstanceKeyName:
        default: SSH Key
      InstanceSubnet:
        default: Subnet

Resources:
  # Elastic IP address for the instance
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Instance
  # EC2 instance
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref InstnaceImageID
      InstanceType: !Ref InstanceType
      KeyName: !Ref InstanceKeyName
      SubnetId: !Ref InstanceSubnet
      SecurityGroupIds:
        - !ImportValue 'tutuka-SecurityGroups-ECSSecGroup'
      IamInstanceProfile: !Ref InstanceIAMProfile

      Tags:
        - { Key: Name, Value: !Ref InstanceName }
        - { Key: User, Value: !Ref InstanceUser }  
 
  # IAM profile for the instance
  InstanceIAMProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref 'InstanceIAMRole'
      
  # IAM role attached to the instance profile
  InstanceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
      Path: /
      
  # IAM policy attached to the role
  InstnacePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: InstancePolicy
      Roles:
      - !Ref InstanceIAMRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - cloudformation:Describe*
          Effect: Allow
          Resource: "*"
        - Action:
          - ec2:DescribeInstances
          - ec2:DescribeInstanceStatus
          - ec2:DescribeTags
          - ec2:CreateTags
          Effect: Allow
          Resource: "*"

Outputs:
  InstanceID:
    Description: EC2 instance ID
    Value: !Ref Instance
    Export:
      Name: !Sub '${AWS::StackName}-Instance-ID'